config/routes.rb
RailsBooksLibrary::Application.routes.draw do
  resources :books do
    resources :comments
  end

  resources :users
  resources :cities
  resources :lendings
  
  get "home/index"

  root :to => 'home#index'

end

app/models/lending.rb
require "maglev_record"

class Lending 
  include MaglevRecord::Base
  attr_accessor :lendingDate, :user, :book, :book_id, :user_id
  

  validates :user, :presence => true
  validates :book, :presence => true

end

app/controllers/lendings_controller.rb
require "book.rb"

class LendingsController < ApplicationController
  # GET /lendings
  # GET /lendings.json
  def index
    @lendings = Lending.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @lendings }
    end
  end

  # GET /lendings/1
  # GET /lendings/1.json
  def show
    @lending = Lending.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @lending }
    end
  end

  # GET /lendings/new
  # GET /lendings/new.json
  def new
    @lending = Lending.new
    @all_books = Book.all.collect {|book| [book.title, book.id]}
    @all_user = User.all.collect {|book| [book.name, book.id]}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @lending }
    end
  end

  # GET /lendings/1/edit
  def edit
    @lending = Lending.find(params[:id])
    @all_books = Book.all.collect {|book| [book.title, book.id]}
    @all_user = User.all.collect {|book| [book.name, book.id]}
  end

  # POST /lendings
  # POST /lendings.json
  def create
    @lending = Lending.new(params[:lending])

    respond_to do |format|
      if @lending.save
        format.html { redirect_to @lending, :notice => 'Lending was successfully created.' }
        format.json { render :json => @lending, :status => :created, :location => @lending }
      else
        format.html { render :action => "new" }
        format.json { render :json => @lending.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lendings/1
  # PUT /lendings/1.json
  def update
    @lending = Lending.find(params[:id])

    respond_to do |format|
      if @lending.update_attributes(params[:lending])
        format.html { redirect_to @lending, :notice => 'Lending was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @lending.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lendings/1
  # DELETE /lendings/1.json
  def destroy
    @lending = Lending.find(params[:id])
    @lending.destroy

    respond_to do |format|
      format.html { redirect_to lendings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lendings_helper.rb
module LendingsHelper
end

app/views/lendings/_form.html.erb
<%= form_for(@lending) do |f| %>
  <% if @lending.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lending.errors.count, "error") %> prohibited this lending from being saved:</h2>

      <ul>
      <% @lending.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book %><br />
    <%= f.select(:book_id, @all_books) %>

  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.select(:user_id, @all_user) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lendings/create.html.erb
It works.

app/views/lendings/edit.html.erb
<h1>Editing lending</h1>

<%= render 'form' %>

<%= link_to 'Show', @lending %> |
<%= link_to 'Back', lendings_path %>

app/views/lendings/index.html.erb
<h1>Listing lendings</h1>

<table>
  <tr>
    <th>Book</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lendings.each do |lending| %>
  <tr>
    <td><%= lending.book %></td>
    <td><%= lending.user %></td>
    <td><%= link_to 'Show', lending %></td>
    <td><%= link_to 'Edit', edit_lending_path(lending) %></td>
    <td><%= link_to 'Destroy', lending, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lending', new_lending_path %>

app/views/lendings/new.html.erb
<h1>New lending</h1>

<%= render 'form' %>

<%= link_to 'Back', lendings_path %>

app/views/lendings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Book:</b>
  <%= @lending.book %>
</p>

<p>
  <b>User:</b>
  <%= @lending.user %>
</p>


<%= link_to 'Edit', edit_lending_path(@lending) %> |
<%= link_to 'Back', lendings_path %>